package com.nt.domain;
// Generated Apr 13, 2018 5:46:20 PM by Hibernate Tools 5.1.4.Final

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * IplMatchInfo generated by hbm2java
 */
public class IplMatchInfo implements java.io.Serializable {

	private int matchid;
	private String title;
	private String location;
	private Timestamp matchDate;
	private String finalresult;
	
	

	public IplMatchInfo() {
		System.out.println("IplMatchInfo::0-param constructor");
	}

	public IplMatchInfo(int matchid) {
		this.matchid = matchid;
	}

	public IplMatchInfo(int matchid, String title, String location, Timestamp matchDate, String finalresult) {
		this.matchid = matchid;
		this.title = title;
		this.location = location;
		this.matchDate = matchDate;
		this.finalresult = finalresult;
	}

	public int getMatchid() {
		return this.matchid;
	}

	public void setMatchid(int matchid) {
		this.matchid = matchid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Timestamp getMatchDate() {
		return this.matchDate;
	}

	public void setMatchDate(Timestamp matchDate) {
		this.matchDate = matchDate;
	}

	public String getFinalresult() {
		return this.finalresult;
	}

	public void setFinalresult(String finalresult) {
		this.finalresult = finalresult;
	}

}
